Working with Neural Network Models

© Hans Nieminen, Satakunta University of Applied Sciences

# Exercise 10.1

In [ ]:
import numpy as np

In [ ]:
def convolution(matrix, kernel, stride=1, padding=0):
    # Add padding to the matrix
    if padding > 0:
        matrix = np.pad(matrix,
                        pad_width=padding,
                        mode='constant',
                        constant_values=0)
    n = matrix.shape[0]
    f = kernel.shape[0]
    conv_matrix = []
    # stepping from top to bottom
    for i in range(0,n-f+1,stride):
        # stepping from left to right
        row = []
        for j in range(0,n-f+1,stride):
            sub_matrix = matrix[i:i+f,j:j+f]
            row.append(sub_matrix.flatten().dot(kernel.flatten()))
        conv_matrix.append(row)
    conv_matrix = np.array(conv_matrix)
    return conv_matrix

In [ ]:
m = np.array([[0.6,0.2,0.2,-0.2,1.1,0.5],
              [0.2,0.4,0.0,0.6,-0.1,0.8],
              [0.3,0.8,0.2,0.3,1.2,1.5],
              [-0.6,0.8,0.8,-0.7,0.1,0.2] ,
              [0.1,0.1,0.1,0.8,0.9,1.2],
              [0.2,-0.5,0.1,-0.3,0.5,0.2]])
m

array([[ 0.6,  0.2,  0.2, -0.2,  1.1,  0.5],
       [ 0.2,  0.4,  0. ,  0.6, -0.1,  0.8],
       [ 0.3,  0.8,  0.2,  0.3,  1.2,  1.5],
       [-0.6,  0.8,  0.8, -0.7,  0.1,  0.2],
       [ 0.1,  0.1,  0.1,  0.8,  0.9,  1.2],
       [ 0.2, -0.5,  0.1, -0.3,  0.5,  0.2]])

In [ ]:
kernel1 = np.array([[1.0, 0.0, 0.5],
                    [0.5, 1.0, 0.5],
                    [0.1, 0.8, 0.2]])
kernel2 = np.array([[0.1, 0.5],
                    [0.5, 1.0]])

In [ ]:
feature_map1 = convolution(m, kernel1, stride=2, padding=2)
feature_map1

array([[ 0.12,  0.26,  0.08,  0.51],
       [ 0.46,  1.91,  1.8 ,  3.17],
       [-0.13,  1.41,  1.38,  2.5 ],
       [ 0.15, -0.2 ,  0.55,  1.35]])

In [ ]:
feature_map2 = convolution(feature_map1, kernel2, stride=1, padding=1)
feature_map2

array([[ 0.12 ,  0.32 ,  0.21 ,  0.55 ,  0.255],
       [ 0.52 ,  2.282,  2.821,  4.333,  1.636],
       [ 0.1  ,  2.346,  3.176,  4.955,  1.567],
       [ 0.085,  0.567,  1.281,  3.013,  0.925],
       [ 0.075, -0.085,  0.255,  0.73 ,  0.135]])

In [ ]:
print(f'Mean is {feature_map2.mean().round(2)}')

Mean is 1.29


# Exercise 10.2

In [ ]:
def count_result_n(n, p, f, s):
    return ((n+2*p-f)/s)+1

In [ ]:
n = 400  # input size: n X n
f = 10  # filter size: f X f
p = 0   # padding
s = 3   # stride

In [ ]:
n = count_result_n(n, p, f, s)
n

131.0

In [ ]:
f = 5  # filter size: f X f
p = 1   # padding
s = 2   # stride

In [ ]:
result_n = count_result_n(n, p, f, s)
result_n

65.0

In [ ]:
dropout = 0.2
output_size = (result_n**2)*(1-dropout)
output_size

3380.0